/* 
* lcd.h
* Created: 23/03/21 01:15:58 PM
* Author: Bitboot Team
*/ 

#ifndef COLOR_SENSOR_H_
#define COLOR_SENSOR_H_

// Configure Pins of Color Sensor
void color_sensor_pin_config(void);

// Interrupt Enable
void color_sensor_pin_interrupt_init(void); //Interrupt 0 enable

// Initialise Devices
void init_devices(void);

// Used to select red filter
void filter_red(void);

// Used to select green filter
void filter_green(void);	

// Used to select blue filter
void filter_blue(void);

// Select no filter
void filter_clear(void);

//This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 20% scaling is preferable.
void color_sensor_scaling();

// Function to select red filter 
void red_read(void);

// Function to select green filter 
void green_read(void);

// Function to select blue filter 
void blue_read(void);

// Function to return color
int color_type(void);

#endif
